version: 2.1
orbs:
  node: circleci/node@4.1.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
      - image: 'circleci/mariadb:latest'
        environment:
          MYSQL_USER: drop
          MYSQL_PASSWORD: drops
          MYSQL_DATABASE: code_drops_test
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: 
          command: node --version
          name: Show node version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: |
            pwd
            touch .env
            echo HOST_PORT=${HOST_PORT} >> .env
            echo DB_USER=${DB_USER} >> .env
            echo DB_PASS=${DB_PASS} >> .env
            echo DB_HOST=${DB_HOST} >> .env
            echo DB_DATABASE_TEST=${DB_DATABASE_TEST} >> .env
            echo SESSION_SECRET=${SESSION_SECRET} >> .env
            cat .env
          name: Create dotenv file
      - run:
          command: yarn test
          name: Run YARN tests

      
    
     


      







