version: 2.1
orbs:
  node: circleci/node@4.1.1
  heroku: circleci/heroku@1.2.5

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches: # Will only deploy on master branch
              only: master 
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
      - image: 'circleci/mariadb:latest'
        environment:
          MYSQL_USER: drop_db_test
          MYSQL_PASSWORD: drop_db_test_pass 
          MYSQL_DATABASE: code_drops_test
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: 
          command: node --version
          name: Show node version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: |
            pwd
            touch .env
            echo HOST_PORT=${HOST_PORT} >> .env
            echo DB_USER=${DB_USER} >> .env
            echo DB_PASS=${DB_PASS} >> .env
            echo DB_HOST=${DB_HOST} >> .env
            echo DB_DATABASE_TEST=${DB_DATABASE_TEST} >> .env
            echo SESSION_SECRET=${SESSION_SECRET} >> .env
            cat .env
          name: Create dotenv file
      - run:
          name: Waiting for MariaDB to start
          command: |
            for i in `seq 1 20`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MariaDB && exit 1
      - run:
          command: yarn test
          name: Run YARN tests

      
    
     


      







