export const ADD_ANNOTATION = "ADD_ANNOTATION";
export const DELETE_ANNOTATION = "DELETE_ANNOTATION";
export const SAVE_ANNOTATION = "SAVE_ANNOTATION";
export const SET_ANNOTATION_EDIT_STATUS = "SET_ANNOTATION_EDIT_STATUS";

export const UPLOAD_DROP = "UPLOAD_DROP";
export const UPLOAD_DROP_BEGIN = "UPLOAD_DROP_BEGIN";
export const UPLOAD_DROP_SUCCESS = "UPLOAD_DROP_SUCCESS";
export const UPLOAD_DROP_FAIL = "UPLOAD_DROP_FAIL";
