export const ADD_ANNOTATION = "ADD_ANNOTATION";
export const DELETE_ANNOTATION = "DELETE_ANNOTATION";
export const SAVE_ANNOTATION = "SAVE_ANNOTATION";
export const SET_ANNOTATION_EDIT_STATUS = "SET_ANNOTATION_EDIT_STATUS";

export const UPLOAD_DROP = "UPLOAD_DROP";
export const UPLOAD_DROP_BEGIN = "UPLOAD_DROP_BEGIN";
export const UPLOAD_DROP_SUCCESS = "UPLOAD_DROP_SUCCESS";
export const UPLOAD_DROP_FAIL = "UPLOAD_DROP_FAIL";

export const SET_EDITOR_THEME = "SET_EDITOR_THEME";
export const SET_EDITOR_LANG = "SET_EDITOR_LANG";
export const SET_EDITOR_FONT_SIZE = "SET_EDITOR_FONT_SIZE";
export const SET_EDITOR_KEYMAP = "SET_EDITOR_KEYMAP";
export const SET_EDITOR_TAB_SIZE = "SET_EDITOR_TAB_SIZE";
export const SET_EDITOR_LINE_WRAP = "SET_EDITOR_LINE_WRAP";
export const SET_EDITOR_INSTANCE = "SET_EDITOR_INSTANCE";
